apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/* # location of all the deployment files to apply the deployment and delete them
build: # Docker build
  local:
    push: false
  # googleCloudBuild:
  #   projectId: ticketing-dev-425721
  artifacts:
    - image: rpate467/auth #us.gcr.io/ticketing-dev-425721/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rpate467/client #us.gcr.io/ticketing-dev-425721/auth
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.ts'
            dest: .
    - image: rpate467/tickets #us.gcr.io/ticketing-dev-425721/auth
      context: tickets
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rpate467/orders #us.gcr.io/ticketing-dev-425721/auth
      context: orders
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rpate467/expiration
      context: expiration
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: rpate467/payments
      context: payments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .